/*
 * App URI: chart-3d/test1
 * Source Location: chart-3d/test1.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("chart-3d/test1", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * test1.js
			 * Created at 2022. 3. 22. 오후 3:25:21.
			 *
			 * @author 염형진
			 ************************************************/
			
			var util = createCommonUtil();
			
			
			/*
			 * 임베디드 페이지에서 load 이벤트 발생 시 호출.
			 * 페이지의 Load가 완료되었을 때 호출되는 Event.
			 */
			function onEp1Load(/* cpr.events.CEvent */ e){
				/** 
				 * @type cpr.controls.EmbeddedPage
				 */
				var ep1 = e.control;
				
				getList1();
			}
			
			/*
			 * 임베디드 페이지에서 load 이벤트 발생 시 호출.
			 * 페이지의 Load가 완료되었을 때 호출되는 Event.
			 */
			function onEp2Load(/* cpr.events.CEvent */ e){
				/** 
				 * @type cpr.controls.EmbeddedPage
				 */
				var ep2 = app.lookup("ep2");
				
				getList2();
			}
			
			function getList1() {
			   
			//    util.Submit.send(app, "subEp1", function(pbSuccess) {
			//        if (pbSuccess) {
			            var dsList = app.lookup("dsList");
			            
			            var jsonArray = new Array();
			            
			            var date = "";
			            var mathScore = "";
			            var engScore = "";
			            var koreanScore = "";
			            
			            var jsonObj = {};
			            
			            if(dsList.getRowCount() == 0){
			                jsonObj.date = dsList.getValue(0, "");
			                jsonObj.mathScore = dsList.getValue(0, 0);
			                jsonObj.engScore = dsList.getValue(0, 0);
			                jsonObj.koreanScore = dsList.getValue(0, 0);
			                jsonArray.push(jsonObj);
			            }
			           
			            for (var i = 0; i < dsList.getRowCount(); i++) {
			                var jsonObj = {};
			                jsonObj.date = dsList.getValue(i, "date");
			                jsonObj.mathScore = dsList.getValue(i, "mathScore");
			                jsonObj.engScore = dsList.getValue(i, "engScore");
			                jsonObj.koreanScore = dsList.getValue(i, "koreanScore");
			                jsonArray.push(jsonObj);
			            }
			            setDrawChart1(jsonArray);
			//        }
			//    });
			}
			
			function setDrawChart1(jsonArray) {
				
			    var ep1 = app.lookup("ep1");
			    
			    ep1.callPageMethod("sendData", jsonArray);
			}
			
			function getList2() {
			   
			//    util.Submit.send(app, "subEp1", function(pbSuccess) {
			//        if (pbSuccess) {
			            var dsList2 = app.lookup("dsList2");
			            
			            var jsonArray = new Array();
			            
			            var date = "";
			            var mathScore = "";
			            var engScore = "";
			            var koreanScore = "";
			            
			            var jsonObj = {};
			            var grd1 = app.lookup("grd1");
			            
			            if(dsList2.getRowCount() == 0){
			                jsonObj.date = dsList2.getValue(0, "");
			                jsonObj.mathScore = dsList2.getValue(0, 0);
			                jsonObj.engScore = dsList2.getValue(0, 0);
			                jsonObj.koreanScore = dsList2.getValue(0, 0);
			                jsonArray.push(jsonObj);
			            }
			           
			            for (var i = 0; i < dsList2.getRowCount(); i++) {
			                var jsonObj = {};
			                jsonObj.date = dsList2.getValue(i, "date");
			                jsonObj.mathScore = dsList2.getValue(i, "mathScore");
			                jsonObj.engScore = dsList2.getValue(i, "engScore");
			                jsonObj.koreanScore = dsList2.getValue(i, "koreanScore");
			                jsonArray.push(jsonObj);
			            }
			            setDrawChart2(jsonArray);
			//        }
			//    });
			}
			
			function setDrawChart2(jsonArray) {
				
			    var ep2 = app.lookup("ep2");
			    
			    ep2.callPageMethod("sendData", jsonArray);
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("dsList");
			dataSet_1.parseData({
				"columns": [
					{"name": "date"},
					{"name": "mathScore"},
					{"name": "engScore"},
					{"name": "koreanScore"}
				],
				"rows": [
					{"date": "계정계DB #1", "mathScore": "58", "engScore": "52", "koreanScore": "52"},
					{"date": "계정계DB #2", "mathScore": "67", "engScore": "56", "koreanScore": "56"},
					{"date": "배치DB #1", "mathScore": "77", "engScore": "68", "koreanScore": "67"},
					{"date": "배치DB #2", "mathScore": "62", "engScore": "56", "koreanScore": "55"},
					{"date": "대외EAI/FEP #1", "mathScore": "12", "engScore": "12", "koreanScore": "12"},
					{"date": "대내EAI #1", "mathScore": "9", "engScore": "6", "koreanScore": "5"},
					{"date": "정보계DB #1", "mathScore": "70", "engScore": "68", "koreanScore": "68"},
					{"date": "정보계DB #2", "mathScore": "61", "engScore": "54", "koreanScore": "54"},
					{"date": "통합AP #1", "mathScore": "38", "engScore": "34", "koreanScore": "33"},
					{"date": "통합AP #2", "mathScore": "38", "engScore": "34", "koreanScore": "33"},
					{"date": "통합AP #3", "mathScore": "39", "engScore": "34", "koreanScore": "33"},
					{"date": "통합AP #4", "mathScore": "38", "engScore": "34", "koreanScore": "32"},
					{"date": "매매AP #1", "mathScore": "35", "engScore": "27", "koreanScore": "27"},
					{"date": "매매AP #2", "mathScore": "32", "engScore": "25", "koreanScore": "25"}
				]
			});
			app.register(dataSet_1);
			
			var dataSet_2 = new cpr.data.DataSet("dsList2");
			dataSet_2.parseData({
				"columns": [
					{"name": "date"},
					{"name": "mathScore"},
					{"name": "engScore"},
					{"name": "koreanScore"}
				],
				"rows": [
					{"date": "202201", "mathScore": "30", "engScore": "60", "koreanScore": "10"},
					{"date": "202202", "mathScore": "50", "engScore": "40", "koreanScore": "50"},
					{"date": "202203", "mathScore": "20", "engScore": "80", "koreanScore": "40"},
					{"date": "202204", "mathScore": "70", "engScore": "70", "koreanScore": "30"},
					{"date": "202205", "mathScore": "50", "engScore": "90", "koreanScore": "80"},
					{"date": "202206", "mathScore": "40", "engScore": "30", "koreanScore": "70"},
					{"date": "202207", "mathScore": "90", "engScore": "40", "koreanScore": "40"},
					{"date": "202208", "mathScore": "20", "engScore": "60", "koreanScore": "38"},
					{"date": "202209", "mathScore": "40", "engScore": "10", "koreanScore": "60"}
				]
			});
			app.register(dataSet_2);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.horizontalMargin = "20px";
			formLayout_1.verticalMargin = "20px";
			formLayout_1.setColumns(["1fr", "1fr"]);
			formLayout_1.setRows(["150px", "1fr", "1fr"]);
			container.setLayout(formLayout_1);
			
			// UI Configuration
			var embeddedPage_1 = new cpr.controls.EmbeddedPage("ep1");
			embeddedPage_1.src = "chart-3d/chart.html";
			if(typeof onEp1Load == "function") {
				embeddedPage_1.addEventListener("load", onEp1Load);
			}
			container.addChild(embeddedPage_1, {
				"colIndex": 0,
				"rowIndex": 1,
				"colSpan": 2,
				"rowSpan": 1
			});
			
			var embeddedPage_2 = new cpr.controls.EmbeddedPage("ep2");
			embeddedPage_2.src = "chartExport/chart2.html";
			if(typeof onEp2Load == "function") {
				embeddedPage_2.addEventListener("load", onEp2Load);
			}
			container.addChild(embeddedPage_2, {
				"colIndex": 1,
				"rowIndex": 2
			});
			
			var grid_1 = new cpr.controls.Grid("grd1");
			grid_1.init({
				"dataSet": app.lookup("dsList2"),
				"columns": [
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"}
				],
				"header": {
					"rows": [{"height": "30px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.targetColumnName = "date";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "날짜";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.targetColumnName = "mathScore";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "수학점수";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.targetColumnName = "engScore";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "영어점수";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.targetColumnName = "koreanScore";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "국어점수";
							}
						}
					]
				},
				"detail": {
					"rows": [{"height": "30px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.columnName = "date";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.columnName = "mathScore";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.columnName = "engScore";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.columnName = "koreanScore";
							}
						}
					]
				}
			});
			container.addChild(grid_1, {
				"colIndex": 0,
				"rowIndex": 2
			});
			
			var grid_2 = new cpr.controls.Grid("grd2");
			grid_2.init({
				"dataSet": app.lookup("dsList"),
				"columns": [
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"}
				],
				"header": {
					"rows": [{"height": "30px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.targetColumnName = "date";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "업무";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.targetColumnName = "mathScore";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "최대";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.targetColumnName = "engScore";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "평균";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.targetColumnName = "koreanScore";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "Peak 평균";
							}
						}
					]
				},
				"detail": {
					"rows": [{"height": "30px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.columnName = "date";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.columnName = "mathScore";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.columnName = "engScore";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.columnName = "koreanScore";
							}
						}
					]
				}
			});
			container.addChild(grid_2, {
				"colIndex": 0,
				"rowIndex": 0,
				"colSpan": 2,
				"rowSpan": 1
			});
		}
	});
	app.title = "test1";
	cpr.core.Platform.INSTANCE.register(app);
})();
